// End-user business-intelligence workspace.
//
// The shell is public, but it contains no credential. Users enter a scoped
// PORTAL_TOKEN, typed once and kept in a first-party cookie, sent only as a bearer header.
// The same page also accepts LAB_TOKEN for owner testing.
export function page(): string {
  return String.raw`<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#151515"><title>EE Business Intelligence</title>
<style>
:root{--paper:#f3f0e8;--sheet:#fbfaf6;--ink:#151515;--muted:#6c6a64;--faint:#9b988f;--line:#cbc6ba;--soft:#e6e1d6;--accent:#2759ff;--accent-dark:#1741d0;--ok:#15785a;--warn:#a36b00;--bad:#9e382f;--display:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif;--sans:Inter,"Helvetica Neue",Arial,sans-serif;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace}
*{box-sizing:border-box}html{background:var(--paper);scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 var(--sans);-webkit-font-smoothing:antialiased}button,input,select{font:inherit}button,a{-webkit-tap-highlight-color:transparent}.hidden{display:none!important}
.app{min-height:100vh}.mast{height:68px;background:var(--ink);color:var(--sheet)}.mast-inner{height:100%;max-width:1180px;margin:auto;padding:0 28px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px;font:750 11px/1 var(--sans);letter-spacing:.13em;text-transform:uppercase}.mark{display:grid;place-items:center;width:30px;height:30px;background:var(--sheet);color:var(--ink);font:850 10px/1 var(--sans)}.desktop-nav{display:flex;align-items:center;gap:6px}.nav-button{border:0;background:transparent;color:#aaa79f;min-height:42px;padding:0 14px;font:700 10px/1 var(--sans);text-transform:uppercase;letter-spacing:.11em;cursor:pointer}.nav-button.active{color:#fff}.access{display:flex;align-items:center;gap:9px;margin-left:16px;padding-left:18px;border-left:1px solid #3b3b38;color:#c9c6be;font:600 10px/1 var(--mono);text-transform:uppercase}.access-dot{width:7px;height:7px;border-radius:50%;background:#50d09d}.signout{border:0;background:transparent;color:#85837d;padding:8px;cursor:pointer;font:600 10px/1 var(--mono)}
.content{max-width:1180px;margin:auto;padding:0 28px 96px}.view{display:none}.view.active{display:block}.hero{position:relative;margin:0 -28px;padding:64px max(28px,calc((100vw - 1180px)/2 + 28px)) 118px;background:var(--ink);color:var(--sheet);overflow:hidden}.hero:after{content:"EE / FIELD INTELLIGENCE";position:absolute;right:30px;bottom:23px;color:#41413e;font:600 9px/1 var(--mono);letter-spacing:.16em}.eyebrow{display:flex;align-items:center;gap:10px;color:#91a8ff;font:700 10px/1 var(--sans);letter-spacing:.17em;text-transform:uppercase}.eyebrow:before{content:"";width:30px;height:2px;background:var(--accent)}.hero h1{max-width:820px;margin:18px 0 18px;font:400 clamp(48px,7vw,86px)/.92 var(--display);letter-spacing:-.055em;text-wrap:balance}.hero p{max-width:610px;margin:0;color:#aaa9a4;font-size:15px;line-height:1.65}.search-sheet{position:relative;margin:-72px 0 0;background:var(--sheet);border:1px solid var(--ink);padding:28px;box-shadow:0 18px 50px rgba(20,20,20,.09)}.search-grid{display:grid;grid-template-columns:1.3fr 1fr 110px auto;align-items:end;gap:18px}.field label{display:block;margin:0 0 8px;font:750 9px/1 var(--sans);letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}.input{width:100%;height:49px;border:0;border-bottom:1px solid var(--ink);border-radius:0;background:transparent;color:var(--ink);padding:0 2px;font-size:16px;outline:none}.input:focus{border-bottom:2px solid var(--accent)}.input::placeholder{color:#aaa69d}.select{appearance:none;background-image:linear-gradient(45deg,transparent 50%,var(--ink) 50%),linear-gradient(135deg,var(--ink) 50%,transparent 50%);background-position:calc(100% - 14px) 21px,calc(100% - 9px) 21px;background-size:5px 5px;background-repeat:no-repeat}.primary{height:49px;border:1px solid var(--accent);background:var(--accent);color:#fff;padding:0 24px;font:800 10px/1 var(--sans);letter-spacing:.11em;text-transform:uppercase;cursor:pointer;white-space:nowrap}.primary:hover{background:var(--accent-dark)}.primary:disabled{opacity:.48;cursor:wait}.form-note{margin:15px 0 0;color:var(--muted);font-size:11px}
.workspace{padding-top:44px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:18px}.section-head h2{margin:0;font:400 clamp(28px,4vw,42px)/1 var(--display);letter-spacing:-.035em}.section-note{max-width:420px;text-align:right;color:var(--muted);font-size:12px}.rule{border-top:1px solid var(--ink)}
.jobs{border-top:1px solid var(--ink);margin-bottom:50px}.job{display:grid;grid-template-columns:125px minmax(0,1fr) auto;gap:20px;align-items:center;min-height:84px;border-bottom:1px solid var(--line)}.job-type{font:700 9px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase;color:var(--accent)}.job-title{font-weight:650;letter-spacing:-.015em}.job-meta{margin-top:5px;font:500 10px/1.4 var(--mono);color:var(--muted);text-transform:uppercase}.job-action{display:flex;align-items:center;gap:12px}.pulse{width:7px;height:7px;border-radius:50%;background:#d29a27;box-shadow:0 0 0 5px rgba(210,154,39,.12);animation:pulse 1.8s infinite}.pulse.done{background:var(--ok);box-shadow:none;animation:none}.pulse.bad{background:var(--bad);box-shadow:none;animation:none}@keyframes pulse{50%{opacity:.38}}.text-action{display:inline-flex;align-items:center;gap:5px;border:0;border-bottom:1px solid currentColor;background:transparent;color:var(--ink);padding:8px 0;text-decoration:none;font:750 10px/1 var(--sans);letter-spacing:.09em;text-transform:uppercase;cursor:pointer}.text-action span{color:var(--accent)}
.result-summary{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--ink);border-bottom:1px solid var(--ink);margin-bottom:26px}.metric{padding:20px 18px 18px 0;min-width:0}.metric+.metric{border-left:1px solid var(--line);padding-left:18px}.metric strong{display:block;overflow:hidden;text-overflow:ellipsis;font:400 34px/1 var(--display);letter-spacing:-.04em}.metric span{display:block;margin-top:8px;color:var(--muted);font:750 8px/1.2 var(--sans);letter-spacing:.13em;text-transform:uppercase}.company-list{border-top:1px solid var(--ink)}.company{display:grid;grid-template-columns:50px minmax(180px,.9fr) minmax(230px,1fr) minmax(270px,1fr);gap:20px;align-items:start;padding:25px 0;border-bottom:1px solid var(--line)}.number{font:550 11px/1 var(--mono);color:var(--accent)}.company h3{margin:0;font-size:17px;line-height:1.2;letter-spacing:-.02em}.meta{margin-top:6px;color:var(--muted);font-size:11px}.address{color:var(--muted);font-size:12.5px}.company-contact{display:grid;gap:13px}.phone{font:500 14px/1.2 var(--mono)}.company-actions{display:flex;align-items:center;gap:13px;flex-wrap:wrap}.research{min-height:41px;border:1px solid var(--ink);background:var(--ink);color:#fff;padding:0 14px;font:750 9px/1 var(--sans);letter-spacing:.09em;text-transform:uppercase;cursor:pointer}.research:hover{background:var(--accent);border-color:var(--accent)}.research:disabled{opacity:.42;cursor:wait}.source-link{color:var(--ink);text-decoration:none;border-bottom:1px solid currentColor;padding:6px 0;font:700 9px/1 var(--sans);letter-spacing:.08em;text-transform:uppercase}.source-link:after{content:" ↗";color:var(--accent)}
.library-hero{padding:64px 0 38px;border-bottom:1px solid var(--ink)}.library-hero h1{margin:12px 0 14px;font:400 clamp(45px,7vw,78px)/.92 var(--display);letter-spacing:-.05em}.library-hero p{max-width:600px;color:var(--muted)}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:25px 0 34px}.filter{min-height:38px;padding:0 14px;border:1px solid var(--line);background:transparent;color:var(--muted);font:700 9px/1 var(--sans);text-transform:uppercase;letter-spacing:.1em;cursor:pointer}.filter.active{background:var(--ink);border-color:var(--ink);color:#fff}.report-list{border-top:1px solid var(--ink)}.report{display:grid;grid-template-columns:130px minmax(0,1fr) 190px auto;gap:22px;padding:27px 0;border-bottom:1px solid var(--line);align-items:start}.report-kind{font:700 9px/1.3 var(--sans);color:var(--accent);letter-spacing:.12em;text-transform:uppercase}.report-date{display:block;margin-top:8px;color:var(--faint);font:500 9px/1 var(--mono)}.report h3{margin:0;font-size:18px;line-height:1.2;letter-spacing:-.02em}.report-summary{margin:8px 0 0;max-width:650px;color:var(--muted);font-size:12.5px}.report-stats{font:500 10px/1.65 var(--mono);color:var(--muted);text-transform:uppercase}.status{display:inline-flex;align-items:center;gap:7px;font:700 9px/1 var(--sans);letter-spacing:.08em;text-transform:uppercase}.status:before{content:"";width:7px;height:7px;border-radius:50%;background:#d29a27}.status.completed:before,.status.partial:before{background:var(--ok)}.status.failed:before{background:var(--bad)}.empty{padding:62px 20px;text-align:center;color:var(--muted);border-bottom:1px solid var(--line)}
.mobile-nav{display:none}.gate{position:fixed;inset:0;z-index:50;display:grid;place-items:center;background:rgba(18,18,18,.92);padding:20px}.gate-panel{width:min(440px,100%);background:var(--sheet);border:1px solid #fff;padding:34px}.gate-mark{display:grid;place-items:center;width:34px;height:34px;background:var(--ink);color:#fff;font:800 10px/1 var(--sans)}.gate h1{margin:32px 0 12px;font:400 42px/.95 var(--display);letter-spacing:-.045em}.gate p{color:var(--muted);font-size:13px}.gate-form{display:grid;grid-template-columns:1fr auto;gap:10px;margin-top:24px}.gate input{height:48px;min-width:0;border:1px solid var(--ink);border-radius:0;background:#fff;padding:0 13px}.gate button{height:48px}.gate-error{min-height:20px;margin:10px 0 0;color:var(--bad)!important;font-size:11px!important}.toast{position:fixed;z-index:60;right:20px;bottom:20px;max-width:380px;background:var(--ink);color:#fff;padding:14px 17px;font-size:12px;box-shadow:0 15px 45px rgba(0,0,0,.2);transform:translateY(140%);transition:transform .24s}.toast.show{transform:translateY(0)}
:focus-visible{outline:2px solid var(--accent);outline-offset:3px}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
@media(max-width:820px){body{padding-bottom:72px}.mast{height:60px}.mast-inner{padding:0 18px}.desktop-nav{display:none}.content{padding:0 18px 44px}.hero{margin:0 -18px;padding:43px 18px 96px}.hero:after{right:18px}.hero h1{font-size:clamp(45px,14vw,64px)}.search-sheet{margin-top:-58px;padding:22px 18px}.search-grid{grid-template-columns:1fr 1fr;gap:18px 14px}.field.keyword{grid-column:1/-1}.search-grid .primary{grid-column:1/-1}.workspace{padding-top:36px}.section-head{display:block}.section-note{text-align:left;margin-top:8px}.job{grid-template-columns:1fr auto;gap:8px 12px;padding:18px 0}.job-type{grid-column:1/-1}.job-action{justify-self:end}.result-summary{grid-template-columns:repeat(2,1fr)}.metric:nth-child(3){border-left:0;border-top:1px solid var(--line);padding-left:0}.metric:nth-child(4){border-top:1px solid var(--line)}.metric strong{font-size:31px}.company{grid-template-columns:35px 1fr;gap:14px 10px;padding:23px 0}.address,.company-contact{grid-column:2}.company-actions{gap:12px}.research{min-height:46px}.library-hero{padding:44px 0 30px}.library-hero h1{font-size:54px}.report{grid-template-columns:1fr auto;gap:12px;padding:23px 0}.report-kind{grid-column:1/-1}.report-stats{grid-column:1}.report>.text-action{grid-column:2;grid-row:2;align-self:end}.mobile-nav{position:fixed;z-index:35;left:0;right:0;bottom:0;display:grid;grid-template-columns:1fr 1fr;height:68px;padding-bottom:env(safe-area-inset-bottom);background:var(--ink);border-top:1px solid #343431}.mobile-tab{border:0;background:transparent;color:#8f8d87;font:700 9px/1 var(--sans);letter-spacing:.11em;text-transform:uppercase}.mobile-tab.active{color:#fff}.mobile-tab span{display:block;width:5px;height:5px;margin:0 auto 8px;border-radius:50%;background:transparent}.mobile-tab.active span{background:var(--accent)}.toast{left:14px;right:14px;bottom:82px;max-width:none}.gate-panel{padding:28px 22px}.gate-form{grid-template-columns:1fr}.gate-form button{width:100%}}
.company-actions .research{display:inline-flex;align-items:center;justify-content:center;min-height:44px;border-color:var(--accent);background:var(--accent);padding:0 17px;font-weight:800;font-size:10px;letter-spacing:.1em;text-decoration:none}.company-actions .research:hover{background:var(--accent-dark);border-color:var(--accent-dark)}.company-actions .research:disabled{opacity:.54}.company-actions .research:before{content:"Direct ";color:#cfd9ff}.company-actions .view-report:before{content:none}.company-actions .view-report{background:var(--ink);border-color:var(--ink)}.company-actions .view-report:hover{background:var(--accent-dark);border-color:var(--accent-dark)}
.mode-tabs{display:flex;flex-wrap:wrap;margin:-4px 0 24px;border-bottom:1px solid var(--soft)}.mode-tab{border:0;background:transparent;color:var(--muted);margin:0 26px 0 0;padding:0 0 11px;border-bottom:2px solid transparent;margin-bottom:-1px;font:750 10px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase;cursor:pointer}.mode-tab.active{color:var(--ink);border-bottom-color:var(--accent)}.company-grid{grid-template-columns:1.3fr 1fr auto}
.report-actions{display:grid;gap:11px;justify-items:end}.people-panel{grid-column:1/-1;margin-top:14px;padding-top:16px;border-top:1px solid var(--soft)}.people-head{margin:0 0 4px;color:var(--muted);font:750 9px/1.3 var(--sans);letter-spacing:.13em;text-transform:uppercase}.people-head+.person-row{border-top:0}.person-row{display:grid;grid-template-columns:36px minmax(0,1fr) auto;gap:16px;align-items:start;padding:13px 0;border-bottom:1px solid var(--soft)}.person-row:last-child{border-bottom:0}.person-rank{font:550 10px/1.6 var(--mono);color:var(--accent)}.person-name{font-weight:650;letter-spacing:-.015em}.person-role{margin-top:3px;color:var(--muted);font-size:12.5px}.person-note{display:inline-block;margin-top:5px;color:var(--faint);font:500 9px/1.4 var(--mono);text-transform:uppercase;text-decoration:none}a.person-note{color:var(--muted);border-bottom:1px solid currentColor}
.vip{display:inline-flex;align-items:center;gap:6px;min-height:38px;border:1px solid var(--ink);background:transparent;color:var(--ink);padding:0 13px;font:750 9px/1 var(--sans);letter-spacing:.09em;text-transform:uppercase;white-space:nowrap;text-decoration:none;cursor:pointer}.vip:hover{background:var(--ink);color:#fff}.vip:disabled{opacity:.45;cursor:wait}
@media(max-width:820px){.company-grid{grid-template-columns:1fr}.mode-tabs{display:grid;grid-template-columns:1fr 1fr;margin-bottom:20px}.mode-tab{margin-right:0;text-align:left;font-size:9px;letter-spacing:.08em}.report-actions{grid-column:2;grid-row:2;align-self:end;gap:9px}.person-row{grid-template-columns:30px minmax(0,1fr);gap:8px 12px}.person-row .vip{grid-column:2;justify-self:start;min-height:44px}}
</style></head><body>
<div id="accessGate" class="gate"><div class="gate-panel"><div class="gate-mark">EE</div><h1>Private intelligence workspace.</h1><p>Enter the access key supplied by the workspace owner. It stays in this browser tab and is never added to a report link.</p><form class="gate-form" onsubmit="connect(event)"><input id="accessKey" type="password" autocomplete="current-password" placeholder="Workspace access key" aria-label="Workspace access key"><button id="connectButton" class="primary" type="submit">Enter</button></form><p id="gateError" class="gate-error" role="alert"></p></div></div>
<div id="portalApp" class="app" aria-hidden="true" inert>
  <header class="mast"><div class="mast-inner"><div class="brand"><span class="mark">EE</span><span>Business intelligence</span></div><nav class="desktop-nav" aria-label="Workspace"><button class="nav-button active" data-view="discover" onclick="switchView('discover')">Discover</button><button class="nav-button" data-view="library" onclick="switchView('library')">Reports</button><span class="access"><span class="access-dot"></span>Connected</span><button class="signout" onclick="disconnect()">Sign out</button></nav><button class="signout" onclick="disconnect()">Exit</button></div></header>
  <main class="content">
    <section id="discoverView" class="view active">
      <div class="hero"><div class="eyebrow">Live market discovery</div><h1>Find the companies worth knowing.</h1><p>Scan a market from the residential Google Maps scout, or look up one company by name. Either way you confirm the business before evidence-guarded deep research starts — and every dossier hands you its people for a VIP brief.</p></div>
      <form id="searchForm" class="search-sheet" onsubmit="startSearch(event)"><div class="mode-tabs" role="tablist" aria-label="Search mode"><button type="button" class="mode-tab active" data-mode="market" onclick="setMode('market')">Discover a market</button><button type="button" class="mode-tab" data-mode="company" onclick="setMode('company')">Research one company</button></div><div class="search-grid" id="marketGrid"><div class="field keyword"><label for="keyword">Business or service <span>(optional)</span></label><input class="input" id="keyword" placeholder="e.g. solar installer"></div><div class="field"><label for="place">Location <span>(optional)</span></label><input class="input" id="place" placeholder="e.g. Kuala Lumpur"></div><div class="field"><label for="maxResults">Results</label><select class="input select" id="maxResults"><option value="100" selected>100</option><option value="200">200</option><option value="300">300</option></select></div><button id="searchButton" class="primary" type="submit">Search market</button></div><div class="search-grid company-grid hidden" id="companyGrid"><div class="field keyword"><label for="companyName">Company name</label><input class="input" id="companyName" placeholder="e.g. Solarvest Holdings Berhad"></div><div class="field"><label for="companyPlace">Location <span>(optional, narrows the match)</span></label><input class="input" id="companyPlace" placeholder="e.g. Petaling Jaya"></div><button id="lookupButton" class="primary" type="submit">Find company</button></div><p class="form-note" id="formNote">Enter a business, a location, or both. A stable report link is created immediately.</p></form>
      <div class="workspace">
        <section id="activeSection" class="hidden"><div class="section-head"><h2>Active work</h2><span class="section-note">Research continues in the background. You may switch views safely.</span></div><div id="jobs" class="jobs"></div></section>
        <section id="searchOutput" class="hidden"><div class="section-head"><h2 id="resultTitle">Search results</h2><span id="resultNote" class="section-note"></span></div><div id="resultSummary" class="result-summary"></div><div id="companies" class="company-list"></div></section>
        <section id="discoverEmpty"><div class="empty">Your latest business list will appear here.</div></section>
      </div>
    </section>
    <section id="libraryView" class="view"><div class="library-hero"><div class="eyebrow">Persistent knowledge base</div><h1>Research library.</h1><p>Browse every market scan, company dossier and VIP brief in one place. Completed public reports keep the same permanent link.</p></div><div class="filters" role="group" aria-label="Report type"><button class="filter active" data-filter="all" onclick="setFilter('all')">All reports</button><button class="filter" data-filter="company_research" onclick="setFilter('company_research')">Company research</button><button class="filter" data-filter="person_research" onclick="setFilter('person_research')">VIP briefs</button><button class="filter" data-filter="business_search" onclick="setFilter('business_search')">Business lists</button></div><div id="reportList" class="report-list"><div class="empty">Loading research library…</div></div></section>
  </main>
  <nav class="mobile-nav" aria-label="Workspace"><button class="mobile-tab active" data-view="discover" onclick="switchView('discover')"><span></span>Discover</button><button class="mobile-tab" data-view="library" onclick="switchView('library')"><span></span>Reports</button></nav>
</div><div id="toast" class="toast" role="status"></div>
<script>
'use strict';
var state={token:'',jobs:{},reports:[],filter:'all',mode:'market',toastTimer:null};
var terminal=['completed','partial','failed'];
function el(id){return document.getElementById(id)}
var TOKEN_KEY='ee_portal_token';
function readToken(){var parts=document.cookie?document.cookie.split(';'):[];for(var i=0;i<parts.length;i++){var p=parts[i].trim();if(p.indexOf(TOKEN_KEY+'=')===0)return decodeURIComponent(p.slice(TOKEN_KEY.length+1))}return ''}
function saveToken(value){var secure=location.protocol==='https:'?';Secure':'';document.cookie=TOKEN_KEY+'='+encodeURIComponent(value)+';path=/;max-age=31536000;SameSite=Strict'+secure}
function dropToken(){var secure=location.protocol==='https:'?';Secure':'';document.cookie=TOKEN_KEY+'=;path=/;max-age=0;SameSite=Strict'+secure}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function attr(value){return esc(value)}
function safeId(value){return /^[A-Za-z0-9_-]{20}$/.test(String(value==null?'':value))?String(value):''}
function safeUrl(value){try{var u=new URL(String(value));return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch(e){return ''}}
function date(value){try{return new Intl.DateTimeFormat('en',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))}catch(e){return 'Undated'}}
function showToast(message){var node=el('toast');node.textContent=message;node.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(function(){node.classList.remove('show')},3600)}
async function api(path,options){options=options||{};var headers=Object.assign({'Authorization':'Bearer '+state.token},options.headers||{});if(options.body)headers['Content-Type']='application/json';var response=await fetch(path,Object.assign({},options,{headers:headers}));var text=await response.text();var body={};try{body=text?JSON.parse(text):{}}catch(e){body={error:text||'Invalid server response'}}if(!response.ok){var message=typeof body.error==='string'?body.error:(body.error&&body.error.message)||('Request failed: '+response.status);var error=new Error(message);error.status=response.status;throw error}return body}
async function connect(event){if(event)event.preventDefault();var key=el('accessKey').value.trim();if(!key)return;state.token=key;el('connectButton').disabled=true;el('gateError').textContent='';try{await api('/api/reports?limit=1');saveToken(key);el('accessGate').classList.add('hidden');el('portalApp').removeAttribute('inert');el('portalApp').setAttribute('aria-hidden','false');await loadLibrary();showToast('Workspace connected')}catch(error){state.token='';el('gateError').textContent=error.status===401?'Access key not accepted.':error.message}finally{el('connectButton').disabled=false}}
function disconnect(){dropToken();state.token='';location.reload()}
function authLost(error){if(error&&error.status===401){dropToken();state.token='';el('accessGate').classList.remove('hidden');el('gateError').textContent='Your access expired. Enter the workspace key again.';return true}return false}
function switchView(name){document.querySelectorAll('.view').forEach(function(node){node.classList.toggle('active',node.id===name+'View')});document.querySelectorAll('[data-view]').forEach(function(node){node.classList.toggle('active',node.getAttribute('data-view')===name)});if(name==='library')loadLibrary();window.scrollTo({top:0,behavior:'smooth'})}
function upsertJob(report,kind){state.jobs[report.id]=Object.assign({},state.jobs[report.id]||{},{report:report,kind:kind});renderJobs()}
function renderJobs(){var values=Object.keys(state.jobs).map(function(key){return state.jobs[key]});el('activeSection').classList.toggle('hidden',values.length===0);el('jobs').innerHTML=values.map(function(job){var r=job.report;var done=terminal.indexOf(r.status)>=0;var pulse=r.status==='failed'?'bad':done?'done':'';var label=job.kind==='search'?'Market scan':job.kind==='lookup'?'Company lookup':job.kind==='vip'?'VIP brief':'Company research';var open=safeUrl(r.view_url);return '<article class="job"><div class="job-type">'+label+'</div><div><div class="job-title">'+esc(r.title)+'</div><div class="job-meta">'+esc(r.status)+' · '+esc(r.id)+'</div></div><div class="job-action"><span class="pulse '+pulse+'"></span>'+(open?'<a class="text-action" target="_blank" rel="noopener" href="'+attr(open)+'">View <span>↗</span></a>':'')+'</div></article>'}).join('')}
function poll(report,kind){upsertJob(report,kind);if(terminal.indexOf(report.status)>=0)return;setTimeout(async function(){try{var body=await api(report.api_url);upsertJob(body.report,kind);if(terminal.indexOf(body.report.status)<0){poll(body.report,kind);return}await loadLibrary();if((kind==='search'||kind==='lookup')&&body.report.status!=='failed'){renderSearch(body,kind)}if(kind==='deep'){showToast(body.report.status==='failed'?'Company research failed':'Company dossier is ready')}if(kind==='vip'){showToast(body.report.status==='failed'?'VIP brief failed':'VIP brief is ready')}if(body.report.status==='failed')showToast(body.report.error||'Research failed')}catch(error){if(!authLost(error)){showToast(error.message);poll(report,kind)}}},5000)}
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(function(node){node.classList.toggle('active',node.getAttribute('data-mode')===mode)});el('marketGrid').classList.toggle('hidden',mode!=='market');el('companyGrid').classList.toggle('hidden',mode!=='company');el('formNote').textContent=mode==='company'?'The name is looked up on Google Maps and the matches come back for you to confirm. Nothing is researched until you pick one.':'Enter a business, a location, or both. A stable report link is created immediately.';setTimeout(function(){el(mode==='company'?'companyName':'keyword').focus()},40)}
async function startLookup(){var name=el('companyName').value.trim();if(!name){showToast('Enter the company name.');el('companyName').focus();return}var place=el('companyPlace').value.trim();var button=el('lookupButton');button.disabled=true;button.textContent='Looking up…';try{var body=await api('/api/business-search',{method:'POST',body:JSON.stringify({keyword:name,place:place||undefined,max:10,requesterId:'portal:company-lookup'})});el('discoverEmpty').classList.add('hidden');upsertJob(body.report,'lookup');poll(body.report,'lookup');showToast('Looking up '+name+' on Google Maps')}catch(error){if(!authLost(error))showToast(error.message)}finally{button.disabled=false;button.textContent='Find company'}}
async function startSearch(event){event.preventDefault();if(state.mode==='company')return startLookup();var keyword=el('keyword').value.trim();var place=el('place').value.trim();if(!keyword&&!place){showToast('Enter a business, a location, or both.');el('keyword').focus();return}var button=el('searchButton');button.disabled=true;button.textContent='Starting…';try{var body=await api('/api/business-search',{method:'POST',body:JSON.stringify({keyword:keyword||undefined,place:place||undefined,max:Number(el('maxResults').value),requesterId:'portal'})});el('discoverEmpty').classList.add('hidden');upsertJob(body.report,'search');poll(body.report,'search');showToast('Market search started')}catch(error){if(!authLost(error))showToast(error.message)}finally{button.disabled=false;button.textContent='Search market'}}
function renderSearch(body,kind){var lookup=kind==='lookup';var companies=(body.data&&body.data.companies)||[];var report=body.report||{};var request=(body.data&&body.data.report&&body.data.report.request)||{};el('searchOutput').classList.remove('hidden');el('discoverEmpty').classList.add('hidden');el('resultTitle').textContent=lookup?'Which one is yours?':(report.title||'Business list');el('resultNote').textContent=lookup?(companies.length+' Google Maps matches · pick the right listing to start deep research on it'):(companies.length+' businesses · use Direct Deep Research to investigate any company');var phones=companies.filter(function(c){return c.phone}).length;var sites=companies.filter(function(c){return c.website}).length;el('resultSummary').innerHTML=metric(companies.length,'Businesses')+metric(phones,'Phone contacts')+metric(sites,'Websites')+metric(report.status==='partial'?'Partial':'Ready','Report status');el('companies').innerHTML=companies.length?companies.map(companyRow).join(''):'<div class="empty">No businesses returned.</div>';setTimeout(function(){el('searchOutput').scrollIntoView({behavior:'smooth',block:'start'})},120)}
function metric(value,label){return '<div class="metric"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>'}
function companyRow(company,index){var website=safeUrl(company.website);var maps=safeUrl(company.maps_url||company.mapsUrl);var phone=company.phone||'';var rating=company.rating?(' · ★ '+company.rating+(company.reviews?' / '+company.reviews+' reviews':'')):'';return '<article class="company"><div class="number">'+String(company.rank||index+1).padStart(2,'0')+'</div><div><h3>'+esc(company.name||'Unnamed business')+'</h3><div class="meta">'+esc(company.category||'Business')+esc(rating)+'</div></div><div class="address">'+esc(company.address||'Address not published')+'</div><div class="company-contact"><div class="phone">'+esc(phone||'Phone not published')+'</div><div class="company-actions"><button class="research" data-company="'+attr(company.id)+'" data-name="'+attr(company.name||'Company')+'" aria-label="Start deep research for '+attr(company.name||'Company')+'" onclick="startResearch(this)">Deep research →</button>'+(phone?'<a class="source-link" href="tel:'+attr(String(phone).replace(/[^+\d]/g,''))+'">Call</a>':'')+(website?'<a class="source-link" target="_blank" rel="noopener" href="'+attr(website)+'">Website</a>':'')+(maps?'<a class="source-link" target="_blank" rel="noopener" href="'+attr(maps)+'">Maps</a>':'')+'</div></div></article>'}
async function startResearch(button){var companyId=button.getAttribute('data-company')||'';var name=button.getAttribute('data-name')||'Company';if(!companyId)return;button.disabled=true;button.textContent='Starting…';try{var body=await api('/api/company-research',{method:'POST',body:JSON.stringify({companyId:companyId,requesterId:'portal'})});var view=safeUrl(body.report&&body.report.view_url);if(view){button.outerHTML='<a class="research view-report" target="_blank" rel="noopener" href="'+attr(view)+'" aria-label="Open research report for '+attr(name)+'">Open report <span>↗</span></a>'}else{button.textContent='Research underway'}upsertJob(body.report,'deep');poll(body.report,'deep');showToast('Deep research started for '+name+'. Open report any time to follow progress.')}catch(error){button.disabled=false;button.textContent='Deep research →';if(!authLost(error))showToast(error.message)}}
async function loadLibrary(){if(!state.token)return;var path='/api/reports?limit=100';if(state.filter!=='all')path+='&type='+encodeURIComponent(state.filter);try{var body=await api(path);state.reports=body.reports||[];renderLibrary();state.reports.forEach(function(report){if(terminal.indexOf(report.status)<0&&!state.jobs[report.id])poll(report,report.type==='business_search'?'search':report.type==='person_research'?'vip':'deep')})}catch(error){if(!authLost(error))showToast(error.message)}}
function setFilter(filter){state.filter=filter;document.querySelectorAll('[data-filter]').forEach(function(node){node.classList.toggle('active',node.getAttribute('data-filter')===filter)});loadLibrary()}
function renderLibrary(){var list=state.reports;el('reportList').innerHTML=list.length?list.map(reportRow).join(''):'<div class="empty">No reports in this view yet.</div>'}
function reportRow(report){var deep=report.type==='company_research';var vip=report.type==='person_research';var ready=deep&&(report.status==='completed'||report.status==='partial');var preview=report.preview||{};var view=safeUrl(report.view_url);var summary=deep?(preview.summary||'Company intelligence report'):vip?(preview.summary||'Public-professional VIP brief'):(preview.keyword?('Market scan for '+preview.keyword+(preview.place?' in '+preview.place:'')):'Business discovery report');var stats=deep?((preview.contacts||0)+' contacts<br>'+(preview.people||0)+' people<br>'+(preview.signals||0)+' signals'):vip?((preview.facts||0)+' facts<br>'+(preview.signals||0)+' signals'):((preview.companies==null?'—':preview.companies)+' companies');return '<article class="report"><div class="report-kind">'+(deep?'Company dossier':vip?'VIP brief':'Business list')+'<span class="report-date">'+date(report.created_at)+'</span></div><div><h3>'+esc(report.title)+'</h3><p class="report-summary">'+esc(summary)+'</p></div><div class="report-stats"><span class="status '+attr(report.status)+'">'+esc(report.status)+'</span><br>'+stats+'</div><div class="report-actions">'+(view?'<a class="text-action" target="_blank" rel="noopener" href="'+attr(view)+'">Open report <span>↗</span></a>':'')+(ready?'<button class="text-action" data-report="'+attr(report.id)+'" aria-expanded="false" onclick="togglePeople(this)">People <span>+</span></button>':'')+'</div>'+(ready?'<div class="people-panel hidden" id="people-'+attr(report.id)+'"></div>':'')+'</article>'}
async function togglePeople(button){var id=button.getAttribute('data-report')||'';var panel=el('people-'+id);if(!panel)return;var open=panel.classList.contains('hidden');panel.classList.toggle('hidden',!open);button.setAttribute('aria-expanded',open?'true':'false');button.innerHTML='People <span>'+(open?'\u2212':'+')+'</span>';if(!open||panel.getAttribute('data-loaded')==='1')return;panel.innerHTML='<div class="empty">Loading people\u2026</div>';try{var body=await api('/api/company-research/'+encodeURIComponent(id));panel.innerHTML=peopleHtml(id,(body.data&&body.data.final)||{});panel.setAttribute('data-loaded','1')}catch(error){panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';if(authLost(error))panel.classList.add('hidden')}}
function peopleHtml(reportId,final){var people=final.people||[];var candidates=final.candidate_people||[];var auto=final.auto_person_research||{};var autoReport=safeId(auto.report_id);var autoPerson=String(auto.person_id==null?'':auto.person_id);var out='';if(people.length){out+='<p class="people-head">Validated people \u00b7 start a VIP brief</p>'+people.map(function(row,i){var pid=String(row.id==null?'':row.id);var role=row.role||row.current_role||row.position||'Role not stated';var evidence=safeUrl(row.role_url||row.role_evidence_url||row.evidence_url);var action;if(pid&&pid===autoPerson&&autoReport){action='<a class="vip" target="_blank" rel="noopener" href="/r/'+attr(autoReport)+'">Open brief <span>\u2197</span></a>'}else if(pid){action='<button class="vip" data-report="'+attr(reportId)+'" data-person="'+attr(pid)+'" aria-label="Start a VIP brief for '+attr(row.name||'this person')+'" onclick="startVip(this)">VIP brief \u2192</button>'}else{action='<span class="person-note">No id \u00b7 cannot be researched</span>'}return '<div class="person-row"><div class="person-rank">P'+String(i+1).padStart(2,'0')+'</div><div><div class="person-name">'+esc(row.name||'Unnamed')+'</div><div class="person-role">'+esc(role)+'</div>'+(evidence?'<a class="person-note" target="_blank" rel="noopener" href="'+attr(evidence)+'">Role evidence \u2197</a>':'<span class="person-note">Role evidence not linked</span>')+'</div>'+action+'</div>'}).join('')}
if(candidates.length){out+='<p class="people-head">Leads to verify \u00b7 role not yet evidenced</p>'+candidates.map(function(row){var source=safeUrl(row.source_url);return '<div class="person-row"><div class="person-rank">\u2014</div><div><div class="person-name">'+esc(row.name||'Unnamed')+'</div><div class="person-role">'+esc(row.role||row.current_role||row.position||'Role not stated')+'</div>'+'<span class="person-note">Named by '+esc(row.source_name||'a public source')+' \u00b7 confirm the role before a brief</span></div>'+(source?'<a class="vip" target="_blank" rel="noopener" href="'+attr(source)+'">Source <span>\u2197</span></a>':'')+'</div>'}).join('')}
return out||'<div class="empty">This dossier validated no people.</div>'}
async function startVip(button){var reportId=button.getAttribute('data-report')||'';var personId=button.getAttribute('data-person')||'';if(!reportId||!personId)return;button.disabled=true;button.textContent='Starting\u2026';try{var body=await api('/api/person-research',{method:'POST',body:JSON.stringify({companyResearchId:reportId,personId:personId,requesterId:'portal'})});var view=safeUrl(body.report&&body.report.view_url);if(view){button.outerHTML='<a class="vip" target="_blank" rel="noopener" href="'+attr(view)+'">Open brief <span>\u2197</span></a>'}else{button.textContent='Brief underway'}upsertJob(body.report,'vip');poll(body.report,'vip');showToast('VIP brief started. Follow it in Active work.')}catch(error){button.disabled=false;button.textContent='VIP brief \u2192';if(!authLost(error))showToast(error.message)}}
(function boot(){var saved=readToken();if(!saved){try{saved=sessionStorage.getItem(TOKEN_KEY)||''}catch(err){saved=''}if(saved)saveToken(saved)}if(saved){el('accessKey').value=saved;connect()}else{setTimeout(function(){el('accessKey').focus()},80)}})();
</script></body></html>`;
}
